### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by D2-mods** [D2-mods/The-Workshop-Kitpack#2]
Hi @11jo , sorry to bother you. I didn't ask you before, so I'll ask now:

1. If I add additional lines to this mod, do you prefer to have a message like this, or would you rather not be contacted?
2. I added a few lines to the French tra to match the English tra. Some of it's translated, based on your own translation. If you want, in the future I can leave the French tra unchanged and only edit the English file, or only add untranslated English text to the file.

Thanks

---

Since I'm messaging you anyways, I'll mention that I added these lines to the tra. These are for items at the bottom of the file:

~ Hunter's Item Sack ~
~ This magical sack was prepared for <CHARNAME> and <PRO_HISHER> allies. The label on the bag reads, "FOR TESTING PURPOSES ONLY". Items within can be removed, but strangely, a magical force prevents the party from placing items into the bag.
~

~ +3% bonus to all Experience gained ~

These aren't very important. 
The bag is for testing items. The 3% XP is for an item that I'm not adding yet in the next update.

**Comment by 11jo** [comment]
No bother at all, on contrary thanks for keeping me updated and for adapting most of the translation !

1. You can send a message anytime

2. What suit you suit me, the fallback in tp2 should replace the missing French translation by the English lines, so both work fine !

...................................

@70124 = ~ Besace du chasseur ~
 @70224 = ~ Cette sacoche magique a été préparée pour  <CHARNAME et ses camarades. On peut lire une étiquette : « POUR EFFECTUER DES TESTS UNIQUEMENT ». Vous pouvez retirer ce qui ce trouve à l'intérieur, mais étrangement, une force surnaturelle empêche le groupe d'y placer de nouveaux objets...

~

@70226 = ~ .....

Bonus de 3 % au gain d'expérience...


~
...................................

Of course I will translate the lines you add in future updates !

Thanks for your work !

**Comment by D2-mods** [comment]
Sounds good. Thanks for the additional lines.
